language: python
install:
  - pip install coveralls
  - pip install tox-travis
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.3
      env:
      - TOXENV=py33
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.5
      env:
      - TOXENV=docs
script:
  - mkdir docs/_static
  - tox
after_success: coveralls
addons:
    code_climate:
        repo_token: 7d980e6d410263f70fb969ade0a0a5086a208d2f2212d493af18b91bb451aafa
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5b086dea7b576065764a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
  email:
    recipients:
      - jenmud@gmail.com
      - jenmud@optiver.com.au
    on_success: change
    on_failure: always
